puyoai/puyoai

src/cpu/test_lockit/coma.cc, src/cpu/test_lockit/coma.h
setti_puyo does not update setti_basyo when there is no place to
put puyos. However, this causes SIGSEGV in chousei_syoukyo etc.
=> Fix setti_puyo.

src/cpu/test_lockit/color.cc, src/cpu/test_lockit/color.h, src/cpu/test_lockit/coma.cc
To reduce possibility of accessing out of range, I add some checks.
=> Avoid accessing out of range in some cases

src/cpu/test_lockit/coma.cc
- introduce a global constant array `kTsumoPatterns`
- make a repeating branch compact.
=> Refactoring of coma.cc

src/cpu/test_lockit/coma.cc, src/cpu/test_lockit/coma.h, src/cpu/test_lockit/field.cc, src/cpu/test_lockit/field.h
saiki() should not be related to COMAI_HI.
=> Extract COMA_HI::saiki to field.

src/cpu/test_lockit/coma.cc, src/cpu/test_lockit/coma.h, src/cpu/test_lockit/field.cc, src/cpu/test_lockit/field.h
There should not be the methods of COMAI_HI.
=> Extract saiki_3 and saiki_4 to field.

src/cpu/test_lockit/coma.cc, src/cpu/test_lockit/coma.h, src/cpu/test_lockit/field.cc, src/cpu/test_lockit/field.h
=> Extract setti_puyo and setti_puyo_1 to field.h

src/cpu/test_lockit/coma.cc, src/cpu/test_lockit/coma.h
We don't have rensa.dat, so read_template does not work at all.
=> Remove COMAI_HI::read_template.

src/cpu/test_lockit/field.cc
=> Replaced magic numbers: '6' to TLColor::OJAMA and '0' to TLColor::EMPTY.

src/cpu/test_lockit/coma.cc
Remove ba2, it's just copied from ba3, and not used.
Use TLColor.
=> [niina] Refactoring: aite_attack_start

src/cpu/test_lockit/coma.cc
=> Replace 0 with TLColor::EMPTY in COMAI_HI::hyouka()

src/cpu/test_lockit/coma.cc
=> Replace 0 with TLColor::EMPTY in COMAI_HI::tobashi_*

src/cpu/test_lockit/coma.cc
=> Replace 0 with TLColor::EMPTY in COMAI_HI::pre_hyouka()

src/cpu/test_lockit/read.cc
=> Replace magic numbers to TLColor in read.cc.

src/cpu/test_lockit/template.cc
=> [niina] Replace magic numbers in templace.cc

src/cpu/test_lockit/coma.cc, src/cpu/test_lockit/coma.h, src/cpu/test_lockit/cpu.cc, src/cpu/test_lockit/field.cc, src/cpu/test_lockit/field.h, src/cpu/test_lockit/field_test.cc, src/cpu/test_lockit/read.cc, src/cpu/test_lockit/read.h, src/cpu/test_lockit/template.cc, src/cpu/test_lockit/template.h, src/cpu/test_lockit/util.cc, src/cpu/test_lockit/util.h
Just replaced int to TLColor for all color variables.
Patch is too big. I'll split this to several pieces...
=> Use TLColor for all color variables.

src/cpu/test_lockit/template.cc
Line number 41 and 67 in the original code had wrong indecies.
=> Refactoring of GTR template checker.

src/cpu/test_lockit/color.h, src/cpu/test_lockit/coma.cc, src/cpu/test_lockit/field.cc, src/cpu/test_lockit/field_test.cc
Define NORMAL_TLCOLORS to convert int to TLColor, and use it.
=> Don't use static_cast to convert int to TLColor.

src/cpu/test_lockit/coma.cc
=> [niina] Refactoing of COMA_HI::aite_hyouka

src/cpu/ryumas/CMakeLists.txt, src/cpu/ryumas/rensa5.cc
I succeeded in making 5 rensa.
But it's just changed the number of sample_rensa, and I have hardly understood contents yet.
=> made 5 rensa maker(rensa5.cc)

src/cpu/test_lockit/coma.cc
Use tobashi_hantei_b in tobashi_hantei_a.
=> [niina] Refactoring of tobashi_hantei

src/cpu/test_lockit/coma.cc, src/cpu/test_lockit/coma.h
=> [niina] Remove unused member variable

src/cpu/test_lockit/coma.cc
=> [niina] Narrow local variable scopes

src/cpu/test_lockit/coma.cc
=> [niina] Use simulate() in coma.cc

src/cpu/test_lockit/coma.cc
=> [niina] Refactoring of 2-double part

src/cpu/test_lockit/coma.cc
BUG= #127
need to be merged after #160
=> [niina] Refactoring a routine to check Zenkeshi

src/cpu/test_lockit/coma.cc
=> [niina] Use simulate in hyouka()

src/cpu/test_lockit/coma.cc
=> [niina] Use simulate in pre_hyouka()

src/cpu/test_lockit/color.cc, src/cpu/test_lockit/color.h, src/cpu/test_lockit/cpu.cc, src/cpu/test_lockit/field.cc, src/cpu/test_lockit/read.cc
This will help us to detect more errors.
=> Make TLColor enum class.

src/cpu/CMakeLists.txt, src/cpu/takapt/CMakeLists.txt, src/cpu/takapt/main.cc, src/cpu/takapt/run.sh
=> Add takapt AI

src/cpu/peria/quick_2dub.cc, src/cpu/peria/quick_full.cc
=> Fix to make cpu/peria compile.

src/cpu/test_lockit/field.cc
saiki_* won't make code faster, but introduces complexity. Better to remove.
=> Refactoring: Remove saiki_* from niina.

.travis.yml
=> Add SDL installation in .travis.yml.
